services:
  dokploy-postgres:
    image: postgres:18.3-alpine3.22
    container_name: dokploy-postgres
    restart: unless-stopped

    environment:
      - POSTGRES_DB=dokploy
      - POSTGRES_USER=dokploy
      - POSTGRES_PASSWORD=dokploy_password

    volumes:
      - dokploy_pg:/var/lib/postgresql/data

    networks:
      - dokploy_net

  dokploy-redis:
    image: redis:8.4.2-alpine3.22
    container_name: dokploy-redis
    restart: unless-stopped

    volumes:
      - dokploy_redis:/data

    networks:
      - dokploy_net

  dokploy:
    image: docker.io/dokploy/dokploy:latest
    container_name: dokploy
    restart: unless-stopped

    depends_on:
      - dokploy-postgres
      - dokploy-redis

    environment:
      - DATABASE_URL=postgres://dokploy:dokploy_password@dokploy-postgres:5432/dokploy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dokploy.rule=Host(`deploy.nenad.cloud`)"
      - "traefik.http.routers.dokploy.entrypoints=websecure"
      - "traefik.http.routers.dokploy.tls.certresolver=le"

    ports:
      - "3000:3000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dokploy_data:/app/data

    networks:
      - dokploy_net
      - proxy

volumes:
  dokploy_data:
  dokploy_pg:
  dokploy_redis:
    driver: local

networks:
  dokploy_net:
  proxy:
    external: true
